---
kind: pipeline
name: nixos-tests

steps:
- name: test
  image: busybox
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
  volumes:
    - name: nixstore
      path: /nix
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  commands:
  - nix flake check
volumes:
- name: nixstore
  host:
    path: /nix
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl
---
kind: signature
hmac: b46736b9787f499301217e1a4022677a32e66fec72a33d02a174aa2485b3c1d2

...
