[package]
name = "cntr"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@higgsboson.tk>"]

[dependencies]
argparse = "0.2.*"
libc = "0.2.8"
log = "*"

[dependencies.nix]
git = "https://github.com/nix-rust/nix"
features = ["signalfd"]

[dependencies.fuse]
git = "https://github.com/zargony/rust-fuse"
