[package]
name = "cntr"
edition = "2018"
description = "A container debugging tool based on FUSE"
version = "1.2.1"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
categories = ["development-tools::debugging", "os::unix-apis"]
repository = "https://github.com/Mic92/cntr"
license = "MIT"

[dependencies]
cpuprofiler = { version = "0.0.*", optional = true }
argparse = "0.2.*"
log = "0.4.*"
tempfile = "3"
num_cpus = "1.13.*"
libc = "0.2.*"
parking_lot = "0.11.*"
void = "1.0.*"
nix = "0.19.*"
#cntr-fuse = "0.3.*"
thread-scoped = "1.0.*"

[dependencies.cntr-fuse]
git = "https://github.com/Mic92/cntr-fuse"
rev = "5c4f80d9aa0d567a8a1fd381c8f4e3c62adbba6c"
branch = "cntrfs"
default-features = false

[dependencies.concurrent-hashmap]
version = "0.2.*"
default-features = false

[[bin]]
name = "cntr"
path = "src/bin/main.rs"

[profile.release]
lto = true

[features]
verbose_fuse_test_log = []
profiling = []
