[package]
name = "cntr"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@higgsboson.tk>"]

[dependencies]
cpuprofiler = {version = "*", optional = true}
argparse = "0.2.*"
log = "*"
time = "*"
tempdir = "0.*"
num_cpus = "1.*"
libc = { git = "https://github.com/rust-lang/libc", branch = "master" }
parking_lot = "*"
serde_json = "1.0"
void = "*"

[dependencies.concurrent-hashmap]
version = "0.2.*"
default-features = false

[dependencies.nix]
path = "src/nix"

[dependencies.fuse]
path = "src/rust-fuse"

[[bin]]
name = "cntr"
path = "src/bin/main.rs"

[lib]
name = "cntr"
path = "src/lib.rs"

[[bin]]
name = "cntrfs-test"
path = "tests/cntrfs.rs"
doc = false

[[bin]]
name = "unserns-test"
path = "tests/userns.rs"
doc = false

[profile.release]
lto = true
debug = true

[features]
default = []
testlogging = []
splice_read = []
splice_write = []
profiling = []
